/**
 * Converts a structured music JSON (from Claude) into Strudel live-coding code.
 */
export function compileToStrudel(json) {
  const { bpm = 120, timeSignature = [4, 4], title = 'Unknown', sections = [] } = json
  const lines = []

  lines.push(`// Generated by Sheet Music to Strudel`)
  lines.push(`// Title: ${title}`)
  lines.push(``)
  lines.push(`setcps(${bpm}/60/4)`)
  lines.push(``)

  // Collect all measures across sections
  const allMeasures = sections.flatMap(s => s.measures ?? [])

  if (allMeasures.length === 0) {
    lines.push(`// No measures found`)
    return lines.join('\n')
  }

  const hasTreble = allMeasures.some(m => m.treble)
  const hasBass = allMeasures.some(m => m.bass)
  const voices = []

  if (hasTreble) {
    const pattern = buildVoicePattern(allMeasures, 'treble')
    voices.push(
      `// Treble clef - melody\n$: ${pattern}\n  .sound("gm_acoustic_grand_piano")\n  .room(0.3)`
    )
  }

  if (hasBass) {
    const pattern = buildVoicePattern(allMeasures, 'bass')
    voices.push(
      `// Bass clef - accompaniment\n$: ${pattern}\n  .sound("gm_acoustic_bass")\n  .room(0.3)`
    )
  }

  if (voices.length > 1) {
    lines.push(voices.join('\n\n'))
  } else if (voices.length === 1) {
    lines.push(voices[0])
  }

  return lines.join('\n')
}

/**
 * Builds a note() pattern string for a single voice across all measures.
 */
function buildVoicePattern(measures, voice) {
  const measureStrings = measures.map(m => buildMeasureString(m[voice] ?? []))
  const n = measureStrings.length

  if (n === 1) {
    return `note("${measureStrings[0]}")`
  }

  const inner = measureStrings.join(' ')
  return `note("<${inner}>/${n}").slow(${n})`
}

/**
 * Converts an array of note objects into a Strudel measure string.
 * Groups consecutive eighth/sixteenth notes into bracket subdivisions.
 */
function buildMeasureString(notes) {
  if (!notes || notes.length === 0) return '~'

  // Group notes by their beat category
  const tokens = []
  let i = 0

  while (i < notes.length) {
    const note = notes[i]
    const dur = note.duration?.toLowerCase() ?? 'quarter'

    if (dur === 'eighth') {
      // Collect consecutive eighth notes into a bracket group
      const group = []
      while (i < notes.length && notes[i].duration?.toLowerCase() === 'eighth') {
        group.push(pitchToken(notes[i].pitch, 'eighth'))
        i++
      }
      tokens.push(`[${group.join(' ')}]`)
    } else if (dur === 'sixteenth') {
      const group = []
      while (i < notes.length && notes[i].duration?.toLowerCase() === 'sixteenth') {
        group.push(pitchToken(notes[i].pitch, 'sixteenth'))
        i++
      }
      tokens.push(`[[${group.join(' ')}]]`)
    } else {
      tokens.push(pitchToken(note.pitch, dur))
      i++
    }
  }

  return tokens.join(' ')
}

function pitchToken(pitch, duration) {
  if (!pitch || pitch === 'rest') return '~'

  const p = pitch.toLowerCase()

  switch (duration?.toLowerCase()) {
    case 'whole':
      return `${p}@4`
    case 'half':
      return `${p}@2`
    case 'dotted_quarter':
    case 'dotted quarter':
      return `${p}@1.5`
    case 'quarter':
    default:
      return p
  }
}
