/**
 * strudelCompiler.js
 *
 * Converts the structured music JSON (from Claude) into idiomatic Strudel
 * live-coding JavaScript.
 *
 * Key design decisions:
 *   - Every note's duration is expressed as an @-weight so the total weights
 *     within each measure bracket sum to the correct beat count.
 *   - Eighth notes are grouped in pairs → [a b]  (1 beat each pair)
 *   - Sixteenth notes grouped in fours → [a b c d]  (1 beat each quad)
 *   - 32nd notes grouped in eights → [a b c d e f g h]  (1 beat each octet)
 *   - Triplets: eighth triplets → [a b c] (1 beat), quarter triplets → [a b c]@2 (2 beats)
 *   - Chords: consecutive notes with chord:true → [c4,e4,g4]
 *   - Multiple sections → arrange(), single section → direct $: patterns
 *   - Never uses .slow() on note patterns; always uses /N inside angle brackets
 */

// ── Strudel syntax reference (also appended to the Claude system prompt) ─────
// Exported so claudeApi.js can append it to SYSTEM_PROMPT, keeping all
// Strudel-specific knowledge in one file.

export const STRUDEL_SYNTAX_REFERENCE = `
=== STRUDEL SYNTAX RULES — MEMORIZE THESE ===

TEMPO:
setcps(BPM/60/4) for 4/4 time
setcps(BPM/60/3) for 3/4 time
Default is 30 cpm = 120 BPM

NOTES:
Use letter + octave: c4 d4 e4 f4 g4 a4 b4
Sharps: f#4 c#5 g#3
Flats: bb3 eb4 ab3
Middle C = c4
Never use MIDI numbers

DURATIONS — these are the ONLY valid ways to express note length:
Whole note = c4@4 (fills entire 4/4 measure)
Half note = c4@2
Dotted half = c4@3
Quarter note = c4 (no modifier needed, default weight = 1)
Dotted quarter = c4@1.5
Two eighth notes in one beat = [c4 d4] (bracket pair, no @ needed)
Single eighth note in a beat = [c4 ~] (eighth + rest)
Four sixteenth notes in one beat = [[c4 d4 e4 f4]]
Eight 32nd notes in one beat = [[[c4 d4 e4 f4 g4 a4 b4 c5]]]
Dotted eighth + sixteenth = [c4@3 d4] (3:1 weight ratio)
Quarter triplet (3 notes over 2 beats) = [c4 e4 g4]@2
Eighth triplet (3 notes over 1 beat) = [c4 e4 g4]
Sixteenth triplet (3 notes over half a beat) = [[c4 e4 g4]]
Rest = ~
Half rest = ~@2
Whole rest = ~@4

NEVER USE THESE — they are invalid Strudel syntax:
@0.5 — INVALID. Use [a b] brackets instead
@0.25 — INVALID. Use [[a b c d]] brackets instead
@0.125 — INVALID. Use [[[...]]] brackets instead
.slow() on a note pattern — INVALID. Use /N inside angle brackets
MIDI numbers like 48 or 60 — avoid, use letter names

CHORDS (multiple notes at same time):
[c4,e4,g4] = C major chord, quarter duration
[c4,e4,g4]@2 = C major chord, half duration

SEQUENCES (multiple measures):
note("<[measure1] [measure2] [measure3]>/3")
The /N number = total number of measures
Each measure's content goes inside square brackets

MULTIPLE VOICES:
$: note("<...>/N").sound("instrument").room(0.3)
$: note("<...>/N").sound("instrument").room(0.3)
Each $: plays simultaneously and independently

SONG SECTIONS with arrange():
const pattern_A = "<[m1] [m2]>/2"
const pattern_B = "<[m3] [m4]>/2"
$: arrange(
  [4, note(pattern_A).sound("piano").room(0.3)],
  [8, note(pattern_B).sound("piano").room(0.3)]
)

INSTRUMENTS:
Piano treble: .sound("gm_acoustic_grand_piano")
Piano bass: .sound("gm_acoustic_bass")
Violin: .sound("gm_violin")
Cello: .sound("gm_cello")
Flute: .sound("gm_flute")
Electric guitar: .sound("gm_electric_guitar_muted")
Bass guitar: .sound("gm_electric_bass_finger")
Synth: .sound("sawtooth") or .sound("square") or .sound("triangle")

EFFECTS (all optional):
.room(0.3) = light reverb (always add this)
.gain(0.8) = volume
.lpf(2000) = low pass filter
.delay(0.3) = echo

VALID COMPLETE EXAMPLE:
// Generated by Sheet Music to Strudel
// Title: Ode to Joy
// Key: C major
// Time: 4/4 | BPM: 104

setcps(104/60/4)

// Treble clef - melody
$: note("<[e4 e4 f4 g4] [g4 f4 e4 d4] [c4 c4 d4 e4] [e4@2 d4@2]>/4")
  .sound("gm_violin")
  .room(0.3)

// Bass clef - accompaniment
$: note("<[c3@2 g3@2] [g2@2 c3@2] [a2@2 e3@2] [c3@4]>/4")
  .sound("gm_acoustic_bass")
  .room(0.3)
`

// ── Duration → beat-length table ─────────────────────────────────────────────
// Reference: quarter note = 1 beat.  Used to compute @-weight modifiers.
// The compiler multiplies these by `beatScale` for non-4/4 time signatures.

const BEAT = {
  'whole':             4,
  'dotted_half':       3,
  'half':              2,
  'dotted_quarter':    1.5,
  'quarter':           1,
  'dotted_eighth':     0.75,
  'eighth':            0.5,
  'dotted_sixteenth':  0.375,
  'sixteenth':         0.25,
  'thirty_second':     0.125,
  'quarter_triplet':   2 / 3,
  'eighth_triplet':    1 / 3,
  'sixteenth_triplet': 1 / 6,
}

// ── Instrument selection ──────────────────────────────────────────────────────

const INSTRUMENT = {
  'treble':   'gm_acoustic_grand_piano',
  'bass':     'gm_acoustic_bass',
  'violin':   'gm_violin',
  'viola':    'gm_viola',
  'cello':    'gm_cello',
  'flute':    'gm_flute',
  'clarinet': 'gm_clarinet',
  'trumpet':  'gm_trumpet',
  'guitar':   'gm_electric_guitar_muted',
}

function getInstrument(voiceName) {
  const lower = voiceName.toLowerCase()
  for (const [key, sound] of Object.entries(INSTRUMENT)) {
    if (lower.includes(key)) return sound
  }
  return 'gm_acoustic_grand_piano' // safe default
}

function getVoiceLabel(voiceName) {
  if (voiceName === 'treble') return 'Right hand (Treble clef)'
  if (voiceName === 'bass')   return 'Left hand (Bass clef)'
  return voiceName
}

// ── Public entry point ────────────────────────────────────────────────────────

/**
 * Main export.  Accepts the validated JSON object from claudeApi.js and
 * returns a complete Strudel JavaScript source string.
 *
 * @param {object} json        Validated music JSON
 * @param {object} patternMap  Visual pattern hints from scoreAnalyzer (reserved for future use)
 * @returns {string}           Strudel source code
 */
export function compileToStrudel(json, patternMap = {}) {  // eslint-disable-line no-unused-vars
  const {
    bpm           = 120,
    timeSignature = [4, 4],
    title         = 'Unknown',
    key           = '',
    sections      = [],
  } = json

  const [tsNum, tsDen] = timeSignature

  // beatScale adjusts @-weights for non-4/4 denominators.
  // For 4/4 and 3/4 (denominator=4): scale = 1, quarter = 1 beat unit.
  // For 6/8 (denominator=8): scale = 2, eighth = 1 beat unit.
  const beatScale = 4 / tsDen

  // setcps divisor = numerator of time signature as specified
  const cpsDivisor = tsNum

  const header = [
    `// Generated by Sheet Music to Strudel`,
    `// Title: ${title}`,
    key ? `// Key: ${key}` : null,
    `// Time: ${tsNum}/${tsDen} | BPM: ${bpm}`,
    ``,
    `setcps(${bpm}/60/${cpsDivisor})`,
    ``,
  ].filter(l => l !== null)

  const allMeasures  = sections.flatMap(s => s.measures ?? [])
  const voiceNames   = getVoiceNames(allMeasures)

  if (voiceNames.length === 0 || allMeasures.length === 0) {
    return [...header, '// No notes detected'].join('\n')
  }

  let body = []

  if (sections.length === 1) {
    // ── Single-section: direct $: patterns ───────────────────────────────────
    body = buildDirectPatterns(sections[0].measures, voiceNames, beatScale)
  } else {
    // ── Multi-section: arrange() ──────────────────────────────────────────────
    body = buildArrangePatterns(sections, voiceNames, beatScale)
  }

  // Run the regex-based validation pass before returning
  return validateStrudel([...header, ...body].join('\n'))
}

// ── Pattern builders ──────────────────────────────────────────────────────────

/**
 * Builds direct $: pattern lines for a single section.
 *
 * When any voice contains repeated measure strings, defines const pattern
 * variables and emits arrange() with run-length-encoded counts instead of a
 * flat note("...") string.  This produces shorter, more readable output for
 * pieces with AABB or verse/chorus-style repetition.
 */
function buildDirectPatterns(measures, voiceNames, beatScale) {
  const lines = []

  // Pre-compute every measure string for every voice
  const voiceMeasureStrs = {}
  for (const voice of voiceNames) {
    voiceMeasureStrs[voice] = measures.map(m =>
      buildMeasureString(m[voice] ?? [], beatScale)
    )
  }

  // Only use pattern variables when there are genuine repeats and enough measures
  const hasRepeats = measures.length > 2 && voiceNames.some(voice => {
    const strs = voiceMeasureStrs[voice]
    return new Set(strs).size < strs.length
  })

  if (!hasRepeats) {
    for (const voice of voiceNames) {
      const pattern = buildNotePattern(measures, voice, beatScale)
      if (!pattern) continue
      lines.push(`// ${getVoiceLabel(voice)}`)
      lines.push(`$: ${pattern}`)
      lines.push(`  .sound("${getInstrument(voice)}")`)
      lines.push(`  .room(0.3)`)
      lines.push(``)
    }
    return lines
  }

  // Assign letter IDs (A, B, C…) to unique measure strings per voice
  const voicePatternIds  = {}  // voice → string[] of IDs, one per measure
  const voicePatternDefs = {}  // voice → Map<id, measureString>

  for (const voice of voiceNames) {
    const strs    = voiceMeasureStrs[voice]
    const strToId = new Map()
    const ids     = []
    let nextCode  = 65 // 'A'

    for (const s of strs) {
      if (!strToId.has(s)) strToId.set(s, String.fromCharCode(nextCode++))
      ids.push(strToId.get(s))
    }
    voicePatternIds[voice]  = ids
    voicePatternDefs[voice] = new Map([...strToId.entries()].map(([s, id]) => [id, s]))
  }

  // Declare const variables
  for (const voice of voiceNames) {
    for (const [id, measureStr] of voicePatternDefs[voice]) {
      lines.push(`const ${voice}_${id} = "[${measureStr}]"`)
    }
  }
  lines.push(``)

  // One arrange() call per voice using run-length-encoded pattern sequence
  for (const voice of voiceNames) {
    const rle   = runLengthEncode(voicePatternIds[voice])
    const sound = getInstrument(voice)
    lines.push(`// ${getVoiceLabel(voice)}`)
    lines.push(`$: arrange(`)
    for (const [id, count] of rle) {
      lines.push(`  [${count}, note(${voice}_${id}).sound("${sound}").room(0.3)],`)
    }
    lines.push(`)`)
    lines.push(``)
  }

  return lines
}

/** Run-length encodes an array into [[value, count], ...] pairs. */
function runLengthEncode(arr) {
  if (arr.length === 0) return []
  const out = [[arr[0], 1]]
  for (let i = 1; i < arr.length; i++) {
    if (arr[i] === out[out.length - 1][0]) out[out.length - 1][1]++
    else out.push([arr[i], 1])
  }
  return out
}

/**
 * Builds arrange()-based patterns for a multi-section piece.
 * Each voice gets its own $: arrange(...) block.
 */
function buildArrangePatterns(sections, voiceNames, beatScale) {
  const lines = []

  // Declare section pattern constants first
  for (const section of sections) {
    for (const voice of voiceNames) {
      const varName = safeVarName(voice, section.name)
      const patStr  = buildPatternString(section.measures, voice, beatScale)
      lines.push(`const ${varName} = "${patStr}"`)
    }
  }
  lines.push(``)

  // Build one arrange() call per voice
  for (const voice of voiceNames) {
    const sound = getInstrument(voice)
    lines.push(`// ${getVoiceLabel(voice)}`)
    lines.push(`$: arrange(`)
    for (const section of sections) {
      const varName = safeVarName(voice, section.name)
      const n = section.measures.length
      lines.push(`  [${n}, note(${varName}).sound("${sound}").room(0.3)],`)
    }
    lines.push(`)`)
    lines.push(``)
  }
  return lines
}

// ── Pattern string builders ───────────────────────────────────────────────────

/**
 * Builds the full note("...") pattern call for one voice across all measures.
 * Returns null if the voice has no notes.
 */
function buildNotePattern(measures, voice, beatScale) {
  const s = buildPatternString(measures, voice, beatScale)
  if (!s) return null
  const n = measures.length
  if (n === 1) return `note("[${buildMeasureString(measures[0][voice] ?? [], beatScale)}]")`
  return `note("${s}")`
}

/**
 * Builds the raw mini-notation string (the part that goes inside note("...")).
 * For N measures: "<[m1] [m2] ... [mN]>/N"
 */
function buildPatternString(measures, voice, beatScale) {
  if (!measures || measures.length === 0) return null

  const parts = measures.map(m => {
    const notes = m[voice] ?? []
    const inner = notes.length === 0
      ? wholeMeasureRest(beatScale)
      : buildMeasureString(notes, beatScale)
    return `[${inner}]`
  })

  const n = parts.length
  if (n === 1) return parts[0]
  return `<${parts.join(' ')}>/${n}`
}

/** Returns a whole-measure rest token (@-weighted for the time signature). */
function wholeMeasureRest(beatScale) {
  // In 4/4 a whole rest = ~@4; beatScale adjusts for other signatures
  const totalBeats = 4 * beatScale
  return `~${beatsToMod(totalBeats)}`
}

// ── Measure string builder ────────────────────────────────────────────────────

/**
 * Converts an array of note objects (one measure's worth) into the space-
 * separated token string that goes inside the measure's square brackets.
 *
 * Handles:
 *   - Chord groups  (chord: true on adjacent notes)
 *   - Triplet groups (eighth_triplet, quarter_triplet, sixteenth_triplet)
 *   - Eighth note pairs → [a b]
 *   - Sixteenth note quads → [a b c d]
 *   - 32nd note octets → [a b c d e f g h]
 *   - All other durations → pitch@beats (or plain pitch for quarter notes)
 */
function buildMeasureString(notes, beatScale) {
  if (!notes || notes.length === 0) return wholeMeasureRest(beatScale)

  const tokens = []
  let i = 0

  while (i < notes.length) {
    const note = notes[i]
    const dur  = (note.duration ?? 'quarter').toLowerCase().trim()

    // ── Chord: collect consecutive chord-marked notes into [p1,p2,p3]@beats ──
    if (note.chord) {
      const chordPitches = []
      const chordDur     = dur
      while (i < notes.length && notes[i].chord) {
        chordPitches.push(pitchStr(notes[i].pitch))
        i++
      }
      const beats = (BEAT[chordDur] ?? 1) * beatScale
      const mod   = beatsToMod(beats)
      tokens.push(`[${chordPitches.join(',')}]${mod}`)
      continue
    }

    // ── Quarter triplets: 3 notes spanning 2 beats → [a b c]@2 ──────────────
    if (dur === 'quarter_triplet') {
      const group = collectRun(notes, i, 'quarter_triplet', 3)
      i += group.length
      const mod = beatsToMod(2 * beatScale)
      tokens.push(`[${group.map(n => pitchStr(n.pitch)).join(' ')}]${mod}`)
      continue
    }

    // ── Eighth triplets: 3 notes spanning 1 beat → [a b c] ───────────────────
    if (dur === 'eighth_triplet') {
      const group = collectRun(notes, i, 'eighth_triplet', 3)
      i += group.length
      const mod = beatsToMod(1 * beatScale)
      tokens.push(`[${group.map(n => pitchStr(n.pitch)).join(' ')}]${mod}`)
      continue
    }

    // ── Sixteenth triplets: 3 notes spanning 0.5 beat → [[a b c]] ────────────
    if (dur === 'sixteenth_triplet') {
      const group = collectRun(notes, i, 'sixteenth_triplet', 3)
      i += group.length
      const mod = beatsToMod(0.5 * beatScale)
      tokens.push(`[[${group.map(n => pitchStr(n.pitch)).join(' ')}]]${mod}`)
      continue
    }

    // ── Eighth notes: collect run, group into pairs (1 beat per pair) ─────────
    if (dur === 'eighth') {
      const run = collectRun(notes, i, 'eighth', Infinity, n => !n.chord)
      i += run.length
      // Process in pairs; a lone trailing eighth uses @0.5
      for (let g = 0; g < run.length; g += 2) {
        const pair = run.slice(g, g + 2)
        if (pair.length === 2) {
          const mod = beatsToMod(1 * beatScale)
          tokens.push(`[${pair.map(n => pitchStr(n.pitch)).join(' ')}]${mod}`)
        } else {
          tokens.push(`${pitchStr(pair[0].pitch)}${beatsToMod(0.5 * beatScale)}`)
        }
      }
      continue
    }

    // ── Sixteenth notes: collect run, group into quads (1 beat per quad) ──────
    if (dur === 'sixteenth') {
      const run = collectRun(notes, i, 'sixteenth', Infinity, n => !n.chord)
      i += run.length
      for (let g = 0; g < run.length; g += 4) {
        const quad = run.slice(g, g + 4)
        const pitches = quad.map(n => pitchStr(n.pitch)).join(' ')
        if (quad.length === 4) {
          tokens.push(`[${pitches}]${beatsToMod(1 * beatScale)}`)
        } else if (quad.length === 2) {
          tokens.push(`[${pitches}]${beatsToMod(0.5 * beatScale)}`)
        } else {
          // 1 or 3 sixteenth notes: emit individually
          quad.forEach(n => tokens.push(`${pitchStr(n.pitch)}${beatsToMod(0.25 * beatScale)}`))
        }
      }
      continue
    }

    // ── 32nd notes: collect run, group into octets (1 beat per octet) ─────────
    if (dur === 'thirty_second') {
      const run = collectRun(notes, i, 'thirty_second', Infinity, n => !n.chord)
      i += run.length
      for (let g = 0; g < run.length; g += 8) {
        const oct    = run.slice(g, g + 8)
        const pitches = oct.map(n => pitchStr(n.pitch)).join(' ')
        tokens.push(`[${pitches}]${beatsToMod(1 * beatScale)}`)
      }
      continue
    }

    // ── All other durations: single token with @-weight ───────────────────────
    const beats = (BEAT[dur] ?? 1) * beatScale
    tokens.push(`${pitchStr(note.pitch)}${beatsToMod(beats)}`)
    i++
  }

  return tokens.length > 0 ? tokens.join(' ') : wholeMeasureRest(beatScale)
}

// ── Token helpers ─────────────────────────────────────────────────────────────

/**
 * Returns the Strudel pitch string for a note.
 * Rests of any duration become "~".
 */
function pitchStr(pitch) {
  if (!pitch || pitch.toLowerCase() === 'rest') return '~'
  return pitch.toLowerCase()
}

/**
 * Returns an @-modifier string for a given beat length.
 * Quarter notes (beats === 1) return '' (no modifier needed — default weight).
 * Fractional values are rounded to 3 decimal places to avoid float noise.
 */
function beatsToMod(beats) {
  const r = Math.round(beats * 1000) / 1000
  if (r === 1) return ''
  return `@${r}`
}

/**
 * Collects a consecutive run of notes with the same duration string,
 * optionally filtered by a predicate.
 *
 * @param {Array}    notes     Full notes array
 * @param {number}   start     Start index
 * @param {string}   durKey    Duration string to match (lowercase)
 * @param {number}   maxLen    Maximum run length (use Infinity for unlimited)
 * @param {Function} [pred]    Optional extra guard per note
 * @returns {Array}  Slice of matched notes
 */
function collectRun(notes, start, durKey, maxLen = Infinity, pred = () => true) {
  const run = []
  let j = start
  while (
    j < notes.length &&
    run.length < maxLen &&
    (notes[j].duration ?? 'quarter').toLowerCase().trim() === durKey &&
    pred(notes[j])
  ) {
    run.push(notes[j])
    j++
  }
  return run
}

// ── Utility helpers ───────────────────────────────────────────────────────────

/** Collects all voice names present across a set of measures. */
function getVoiceNames(measures) {
  const names = new Set()
  for (const m of measures) {
    for (const key of Object.keys(m)) {
      if (Array.isArray(m[key])) names.add(key)
    }
  }
  // Prefer treble first, then bass, then any others
  const priority = ['treble', 'bass']
  return [
    ...priority.filter(p => names.has(p)),
    ...[...names].filter(n => !priority.includes(n)),
  ]
}

/** Creates a valid JS identifier from a voice name and section name. */
function safeVarName(voice, sectionName) {
  const v = voice.replace(/[^a-zA-Z0-9]/g, '_')
  const s = sectionName.replace(/[^a-zA-Z0-9]/g, '_')
  return `${v}_${s}`
}

// ── Syntax validation ─────────────────────────────────────────────────────────

/**
 * Post-processes the generated Strudel code to catch and fix common invalid
 * syntax patterns.  Never throws — always returns the best string it can.
 *
 * Fixes applied (in order):
 *   1. @0.5   → [note ~]  (or bare note for rests)
 *   2. @0.25  → strip modifier, leave note as quarter
 *   3. @0.125 → strip modifier
 *   4. Warn about .slow() on note() lines (not auto-fixed)
 *   5. Warn about mismatched < > inside note strings
 *   6. Detect and repair mismatched [ ] inside note strings
 *   7. Warn about >/0 (invalid /N)
 *
 * All issues are logged to the browser console as warnings so they surface
 * during development without disrupting the user experience.
 *
 * @param {string} code  Generated Strudel source
 * @returns {string}     Cleaned Strudel source
 */
export function validateStrudel(code) {
  const issues = []
  let result = code

  // ── 1. @0.5 → bracket notation ───────────────────────────────────────────
  if (/@0\.5/.test(result)) {
    issues.push('@0.5 modifier found (invalid) — replacing note@0.5 with [note ~], stripping ~@0.5')
    // Named note: c4@0.5 → [c4 ~]
    result = result.replace(/([a-g][b#]?\d)@0\.5/g, '[$1 ~]')
    // Rest eighth: ~@0.5 → bare ~
    result = result.replace(/~@0\.5/g, '~')
    // Any remaining @0.5 (shouldn't happen but catch stragglers)
    result = result.replace(/@0\.5/g, '')
  }

  // ── 2. @0.25 → strip ─────────────────────────────────────────────────────
  if (/@0\.25/.test(result)) {
    issues.push('@0.25 modifier found (invalid) — stripping, note treated as quarter')
    result = result.replace(/@0\.25/g, '')
  }

  // ── 3. @0.125 → strip ────────────────────────────────────────────────────
  if (/@0\.125/.test(result)) {
    issues.push('@0.125 modifier found (invalid) — stripping')
    result = result.replace(/@0\.125/g, '')
  }

  // ── 4. .slow() on note() — warn only ─────────────────────────────────────
  if (/note\([^)]*\)[^;\n]*\.slow\(/.test(result)) {
    issues.push('.slow() found on a note() pattern — use /N inside angle brackets instead (not auto-fixed)')
  }

  // ── 5 & 6. Bracket checks inside note("...") strings ─────────────────────
  // Collect all note("...") calls so we can check their string contents.
  // We operate on a snapshot of matches so mutations to `result` don't
  // invalidate the loop mid-iteration.
  const noteMatches = [...result.matchAll(/note\("([^"]*)"\)/g)]

  for (const m of noteMatches) {
    const original = m[0]
    const patStr   = m[1]

    // 5. Angle bracket balance (warn only — hard to auto-repair)
    const openAngles  = (patStr.match(/</g) ?? []).length
    const closeAngles = (patStr.match(/>/g) ?? []).length
    if (openAngles !== closeAngles) {
      issues.push(`Mismatched angle brackets (${openAngles} < vs ${closeAngles} >) in: ${patStr.slice(0, 60)}`)
    }

    // 6. Square bracket balance — attempt repair by appending missing closers
    const openSquare  = (patStr.match(/\[/g) ?? []).length
    const closeSquare = (patStr.match(/\]/g) ?? []).length
    if (openSquare !== closeSquare) {
      const diff = openSquare - closeSquare
      if (diff > 0) {
        issues.push(`Mismatched [ ] in note pattern (${diff} unclosed) — appending closer(s)`)
        const repaired = `note("${patStr}${']'.repeat(diff)}")`
        result = result.replace(original, repaired)
      } else {
        issues.push(`Mismatched [ ] in note pattern (${Math.abs(diff)} extra closers) — manual review needed`)
      }
    }
  }

  // ── 7. /N must be a positive integer ─────────────────────────────────────
  for (const m of result.matchAll(/>\/(\d+)/g)) {
    if (parseInt(m[1]) <= 0) {
      issues.push(`>/0 found in pattern — /N must be a positive integer`)
    }
  }

  // ── Log all findings ──────────────────────────────────────────────────────
  if (issues.length > 0) {
    console.warn(`[Sheet Music to Strudel] validateStrudel found ${issues.length} issue(s):`)
    issues.forEach(w => console.warn('  ⚠', w))
  }

  return result
}
