/**
 * strudelCompiler.js
 *
 * Converts the structured music JSON returned by Claude into idiomatic Strudel
 * live-coding JavaScript.
 *
 * Supported rhythm features:
 *   - Whole, half, quarter notes (and dotted variants)
 *   - Eighth and sixteenth notes grouped into Strudel bracket subdivisions
 *   - Dotted eighth notes
 *   - Quarter-note triplets  (3 in the time of 2 quarters → [a b c]@2)
 *   - Eighth-note triplets   (3 in the time of 1 quarter  → [a b c])
 *   - Ties: consecutive notes of the same pitch are merged into one longer note
 *   - Rests ("~") for any pitch === "rest"
 */

// ── Duration table ────────────────────────────────────────────────────────────

/**
 * Maps the duration strings Claude uses to their beat lengths (quarter = 1).
 * Used for converting tied notes and for building @-modifier suffixes.
 */
const DURATION_BEATS = {
  'sixteenth':      0.25,
  'dotted_eighth':  0.375,
  'dotted eighth':  0.375,
  'eighth':         0.5,
  'triplet_quarter': 2 / 3,  // one of three notes that together fill 2 beats
  'triplet quarter': 2 / 3,
  'triplet_eighth':  1 / 3,  // one of three notes that together fill 1 beat
  'triplet eighth':  1 / 3,
  'quarter':        1,
  'dotted_quarter': 1.5,
  'dotted quarter': 1.5,
  'half':           2,
  'dotted_half':    3,
  'dotted half':    3,
  'whole':          4,
  'dotted_whole':   6,
  'dotted whole':   6,
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Entry point: converts a validated music JSON object into Strudel code.
 *
 * @param {object} json  Validated output from claudeApi.callClaudeAPI()
 * @returns {string}     Strudel JavaScript source ready to paste/open
 */
export function compileToStrudel(json) {
  const {
    bpm           = 120,
    timeSignature = [4, 4],
    title         = 'Unknown',
    sections      = [],
  } = json

  const lines = []
  lines.push(`// Generated by Sheet Music to Strudel`)
  lines.push(`// Title: ${title}`)
  lines.push(`// Time: ${timeSignature[0]}/${timeSignature[1]}`)
  lines.push(``)
  // setcps converts BPM to cycles-per-second in Strudel's internal unit system
  lines.push(`setcps(${bpm}/60/4)`)
  lines.push(``)

  // Flatten measures across all sections into one sequence
  const allMeasures = sections.flatMap(s => s.measures ?? [])

  if (allMeasures.length === 0) {
    lines.push(`// No measures detected`)
    return lines.join('\n')
  }

  const hasTreble = allMeasures.some(m => m.treble?.length)
  const hasBass   = allMeasures.some(m => m.bass?.length)
  const voices    = []

  if (hasTreble) {
    const pattern = buildVoicePattern(allMeasures, 'treble')
    voices.push(
      `// Treble clef — melody\n$: ${pattern}\n  .sound("gm_acoustic_grand_piano")\n  .room(0.3)`
    )
  }

  if (hasBass) {
    const pattern = buildVoicePattern(allMeasures, 'bass')
    voices.push(
      `// Bass clef — accompaniment\n$: ${pattern}\n  .sound("gm_acoustic_bass")\n  .room(0.3)`
    )
  }

  if (voices.length === 0) {
    lines.push(`// No voices detected in measures`)
  } else {
    lines.push(voices.join('\n\n'))
  }

  return lines.join('\n')
}

// ── Voice / measure builders ──────────────────────────────────────────────────

/**
 * Builds the complete note() pattern string for one voice (treble or bass)
 * across every measure.
 *
 * A single measure becomes  note("...").
 * Multiple measures become  note("<m1 m2 ... mN>/N").slow(N)
 * This uses Strudel's angle-bracket "slow sequence" syntax so each measure
 * occupies exactly one cycle.
 */
function buildVoicePattern(measures, voice) {
  const measureStrings = measures.map(m => buildMeasureString(m[voice] ?? []))
  const n = measureStrings.length

  if (n === 1) {
    return `note("${measureStrings[0]}")`
  }

  return `note("<${measureStrings.join(' ')}>/${n}").slow(${n})`
}

/**
 * Converts an array of note objects (one measure's worth) into a Strudel
 * mini-notation string.
 *
 * Processing order for each note:
 *   1. Tied notes are merged first (accumulated duration wins).
 *   2. Triplet groups are collected into bracket groups.
 *   3. Eighth notes are collected into [group] subdivisions.
 *   4. Sixteenth notes are collected into [[group]] subdivisions.
 *   5. All other durations emit a single token with an @-modifier.
 */
function buildMeasureString(notes) {
  if (!notes || notes.length === 0) return '~'

  const tokens = []
  let i = 0

  while (i < notes.length) {
    const note = notes[i]
    const dur  = (note.duration ?? 'quarter').toLowerCase()

    // ── Tied note ────────────────────────────────────────────────────────────
    // A tie extends the current note's duration by adding the next note's beats.
    // We keep consuming tied notes until we find one without tied:true.
    if (note.tied) {
      let totalBeats = DURATION_BEATS[dur] ?? 1
      i++
      // The tie chain: note[i-1].tied connects to note[i], whose .tied may
      // continue the chain, etc.
      while (i < notes.length && notes[i - 1]?.tied) {
        const nextDur = (notes[i].duration ?? 'quarter').toLowerCase()
        totalBeats += DURATION_BEATS[nextDur] ?? 1
        i++
      }
      tokens.push(pitchWithBeats(note.pitch, totalBeats))
      continue
    }

    // ── Quarter-note triplets: 3 notes spanning 2 beats → [a b c]@2 ─────────
    if (dur === 'triplet_quarter' || dur === 'triplet quarter') {
      const group = []
      while (
        i < notes.length &&
        notes.length > 0 &&
        (notes[i].duration ?? '').toLowerCase().replace(' ', '_') === 'triplet_quarter' &&
        group.length < 3
      ) {
        group.push(pitchToken(notes[i].pitch))
        i++
      }
      tokens.push(`[${group.join(' ')}]@2`)
      continue
    }

    // ── Eighth-note triplets: 3 notes spanning 1 beat → [a b c] ─────────────
    if (dur === 'triplet_eighth' || dur === 'triplet eighth') {
      const group = []
      while (
        i < notes.length &&
        (notes[i].duration ?? '').toLowerCase().replace(' ', '_') === 'triplet_eighth' &&
        group.length < 3
      ) {
        group.push(pitchToken(notes[i].pitch))
        i++
      }
      tokens.push(`[${group.join(' ')}]`)
      continue
    }

    // ── Eighth notes: run of eighths → [a b c …] ─────────────────────────────
    if (dur === 'eighth') {
      const group = []
      while (
        i < notes.length &&
        (notes[i].duration ?? '').toLowerCase() === 'eighth' &&
        !notes[i].tied
      ) {
        group.push(pitchToken(notes[i].pitch))
        i++
      }
      tokens.push(`[${group.join(' ')}]`)
      continue
    }

    // ── Sixteenth notes: run of sixteenths → [[a b c …]] ─────────────────────
    if (dur === 'sixteenth') {
      const group = []
      while (
        i < notes.length &&
        (notes[i].duration ?? '').toLowerCase() === 'sixteenth' &&
        !notes[i].tied
      ) {
        group.push(pitchToken(notes[i].pitch))
        i++
      }
      tokens.push(`[[${group.join(' ')}]]`)
      continue
    }

    // ── All other durations: emit a single token with @-modifier ─────────────
    tokens.push(pitchToken(note.pitch, dur))
    i++
  }

  return tokens.join(' ')
}

// ── Token helpers ─────────────────────────────────────────────────────────────

/**
 * Returns a Strudel pitch token for a given pitch + duration string.
 * Eighth/sixteenth notes have no @-modifier because their subdivision bracket
 * handles timing.  Everything else uses beatsToModifier().
 */
function pitchToken(pitch, duration) {
  if (!pitch || pitch.toLowerCase() === 'rest') return '~'

  const p   = pitch.toLowerCase()
  const dur = (duration ?? 'quarter').toLowerCase()

  // These durations are always inside bracket groups so no @-modifier is needed
  if (dur === 'eighth' || dur === 'sixteenth') return p

  const beats = DURATION_BEATS[dur] ?? 1
  const mod   = beatsToModifier(beats)
  return mod ? `${p}${mod}` : p
}

/**
 * Like pitchToken() but accepts a pre-computed beat count (used for ties where
 * we've already summed up the constituent note durations).
 */
function pitchWithBeats(pitch, beats) {
  if (!pitch || pitch.toLowerCase() === 'rest') return '~'
  const mod = beatsToModifier(beats)
  return mod ? `${pitch.toLowerCase()}${mod}` : pitch.toLowerCase()
}

/**
 * Converts a beat count (quarter = 1) to a Strudel @-modifier string.
 * Quarter notes (1 beat) need no modifier.
 * Fractional values are rounded to 3 decimal places to avoid floating-point noise.
 *
 * Examples:
 *   1   → ''       (quarter — no modifier)
 *   2   → '@2'     (half)
 *   1.5 → '@1.5'   (dotted quarter)
 *   4   → '@4'     (whole)
 */
function beatsToModifier(beats) {
  if (beats === 1) return ''
  // Round to avoid values like 0.30000000000000004
  const rounded = Math.round(beats * 1000) / 1000
  return `@${rounded}`
}
